name: ci
on:
  push:
    branches:
      - 'production'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ildo/nodejs-ops-test:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -  
        
          
          name : runscript ssh to instance
          uses: appleboy/ssh-action@master
          with:
                   host        : ${{ secrets.DEPLOY_SERVER_HOST }}
                   username    : ubuntu
                   key         : ${{ secrets.DEPLOY_SERVER_KEY }}
                   port        : ${{ secrets.PORT }}
                   script:
                               sudo ./dockercleanup.sh
     
        
        
